version: "3.9"

services:
  database:
    image: postgres:16
    volumes:
      - db-volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=my-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

volumes:
  db-volume:
